---
linters:
  enable-all: true
  disable:
  - wsl
  - testpackage
  - godot
  - goerr113
  - funlen
  - godox
  - dupl
  - nestif
  - lll
  - gochecknoglobals
  - nlreturn
  - exhaustivestruct
  - paralleltest # TODO
  - wrapcheck # TODO
